### ISSUE TITLE
How to run the ros_gnss_stereo_inertial?

### ISSUE THREAD

**Issue by LuoXubo** [CIFASIS/gnss-stereo-inertial-fusion#2]
Hi, thanks for your great work!

I've built the GNSS_SI under the ROS directory following your instructions. And the executable file is generated without errors:
```
...
[ 75%] Linking CXX executable Stereo_Inertial
[ 75%] Built target Stereo_Inertial
[100%] Linking CXX executable GNSS_Stereo_Inertial
[100%] Built target GNSS_Stereo_Inertial
```
However, when I run this command:
```
rosrun ORB_SLAM3 GNSS_Stereo_Inertial Vocabulary/ORBvoc.txt Examples/Stereo-Inertial/TUM-VI_far.yaml true
```
There is an error:
```
[rospack] Error: package 'ORB_SLAM3' not found[rospack] Error: package 'ORB_SLAM3' not found[rospack] Error: package 'ORB_SLAM3' not found
```
Could you help me solve this problem?

**Comment by jcremona** [comment]
Hi! Have you followed these steps?
https://github.com/CIFASIS/gnss-stereo-inertial-fusion?tab=readme-ov-file#ros-node
In particular, adding the `export` command to the `.bashrc` file.

**Comment by LuoXubo** [comment]
Thanks for your reply. I've fixed this problem. Instead of `ORB_SLAM3`, I should run this command:
```
rosrun GNSS_SI GNSS_Stereo_Inertial Vocabulary/ORBvoc.txt Examples/Stereo-Inertial/TUM-VI_far.yaml true
```
And I have one more question about the optimization. If there are only two types of source data (like images and GNSS data ) fed into the system, will the estimation be optimized? Or is the estimation optimized only when there are exactly three types of source data (images, GNSS data and IMU data)?

**Comment by jcremona** [comment]
The current implementation of `GNSS_Stereo_Inertial` assumes it receives images, GNSS and IMU as input. Measurements from the three sensors are needed.

**Comment by SrOdranoel** [comment]
@jcremona Hi i want to know if you had ever use the stereo inertial mode of ORB-SLAM 3????? Im trying put to work with my stereo inertial system but im passing for  a lot of problems and looking for someone to help me or give some tip for a solution....

**Comment by jcremona** [comment]
Yes, I did run Stereo-inertial Orbslam3

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SrOdranoel** [comment]
hello Mr @jcremona i having this error log bellow if you had this problem on the pass and know how i can solve can we talk on linkedin, email or discord?
Error log
```
First KF:4; Map init KF:3  
New Map created with 19 points  
TRACK_REF_KF: Less than 15 matches!!  
Fail to track local map!  
LM: Active map reset received  
LM: Active map reset, waiting...  
LM: Resetting current map in Local Mapping...  
LM: End resetting Local Mapping...  
LM: Reset free the mutex  
LM: Active map reset, Done!!!  
mnFirstFrameId = 117  
mnInitialFrameId = 40  
5 Frames set to lost  
not IMU meas  
First KF:5; Map init KF:4  
New Map created with 19 points  
TRACK_REF_KF: Less than 15 matches!!  
Fail to track local map!  
LM: Active map reset received  
LM: Active map reset, waiting...  
LM: Resetting current map in Local Mapping...  
LM: End resetting Local Mapping...  
LM: Reset free the mutex  
LM: Active map reset, Done!!!  
mnFirstFrameId = 120  
mnInitialFrameId = 118  
6 Frames set to lost  
not IMU meas  
not enough acceleration  
not enough acceleration  
not enough acceleration 
```

**Comment by jcremona** [comment]
"not enough acceleration" -> This message is shown when there is no motion. The system does not estimate the robot's position if it's stationary.

**Comment by SrOdranoel** [comment]
yes but when i move it lose and recreate the map:
```
First KF:26; Map init KF:25
New Map created with 149 points
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 262
mnInitialFrameId = 251
90 Frames set to lost
not IMU meas
not enough acceleration
First KF:27; Map init KF:26
New Map created with 134 points
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 274
mnInitialFrameId = 271
98 Frames set to lost
not IMU meas
not enough acceleration
First KF:28; Map init KF:27
New Map created with 101 points
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 284
mnInitialFrameId = 281
100 Frames set to lost
not IMU meas
not enough acceleration
First KF:29; Map init KF:28
New Map created with 109 points
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 288
mnInitialFrameId = 285
102 Frames set to lost
not IMU meas
First KF:30; Map init KF:29
New Map created with 65 points
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 291
mnInitialFrameId = 289
104 Frames set to lost
not IMU meas
First KF:31; Map init KF:30
New Map created with 63 points
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 294
mnInitialFrameId = 292
106 Frames set to lost
not IMU meas
```
i have calibrated using the kalibr and the calibration make sense the IMU position and looks like the IMU in not measuring or send data but i have make some test on hz and looks fine:

rostopic hz /imu/data_raw:

```
average rate: 249.014
	min: 0.002s max: 0.008s std dev: 0.00182s window: 249
average rate: 249.734
	min: 0.002s max: 0.008s std dev: 0.00192s window: 500
average rate: 249.986
	min: 0.002s max: 0.008s std dev: 0.00197s window: 749
average rate: 249.746
	min: 0.002s max: 0.008s std dev: 0.00196s window: 1000
average rate: 249.796
	min: 0.002s max: 0.008s std dev: 0.00197s window: 1250
average rate: 249.833
	min: 0.002s max: 0.008s std dev: 0.00198s window: 1500
average rate: 249.926
	min: 0.002s max: 0.008s std dev: 0.00196s window: 1751
average rate: 249.873
	min: 0.002s max: 0.008s std dev: 0.00196s window: 2001
average rate: 249.999
	min: 0.002s max: 0.008s std dev: 0.00195s window: 2251
average rate: 249.949
	min: 0.002s max: 0.008s std dev: 0.00196s window: 2502
average rate: 249.999
	min: 0.002s max: 0.008s std dev: 0.00196s window: 2753
average rate: 249.999
	min: 0.002s max: 0.008s std dev: 0.00196s window: 3003
average rate: 249.998
	min: 0.002s max: 0.008s std dev: 0.00195s window: 3253
average rate: 249.999
	min: 0.002s max: 0.008s std dev: 0.00196s window: 3504
average rate: 249.966
	min: 0.002s max: 0.008s std dev: 0.00196s window: 3753
average rate: 249.937
	min: 0.002s max: 0.008s std dev: 0.00196s window: 4003
average rate: 249.970
	min: 0.002s max: 0.008s std dev: 0.00196s window: 4254
average rate: 249.942
	min: 0.002s max: 0.008s std dev: 0.00196s window: 4504
^Caverage rate: 249.999
	min: 0.002s max: 0.008s std dev: 0.00196s window: 4528
```
rostopic echo /imu/data_raw:

```
header: 
  seq: 1638107
  stamp: 
    secs: 1742317251
    nsecs: 301854243
  frame_id: "imu_0"
orientation: 
  x: -0.6670404625695785
  y: 0.0944958907840529
  z: 0.08587569936305034
  w: 0.7339978965765488
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.21276633107304652
  y: 0.19293110727413637
  z: 0.08075024004451059
angular_velocity_covariance: [2.7474e-06, 0.0, 0.0, 0.0, 2.7474e-06, 0.0, 0.0, 0.0, 7.312e-06]
linear_acceleration: 
  x: -2.5270611475944516
  y: -9.701754039764404
  z: 1.0251859280586242
linear_acceleration_covariance: [0.00041915, 0.0, 0.0, 0.0, 0.00041915, 0.0, 0.0, 0.0, 1.8995e-05]
---
header: 
  seq: 1638108
  stamp: 
    secs: 1742317251
    nsecs: 305846886
  frame_id: "imu_0"
orientation: 
  x: -0.6659876978407158
  y: 0.09425410704465051
  z: 0.0853995637878917
  w: 0.735039770444346
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.20289452554434081
  y: 0.17795775036127484
  z: 0.08641851210863524
angular_velocity_covariance: [2.7474e-06, 0.0, 0.0, 0.0, 2.7474e-06, 0.0, 0.0, 0.0, 7.312e-06]
linear_acceleration: 
  x: -2.5471499958992
  y: -9.702015905570983
  z: 1.0589479124069214
linear_acceleration_covariance: [0.00041915, 0.0, 0.0, 0.0, 0.00041915, 0.0, 0.0, 0.0, 1.8995e-05]
---
header: 
  seq: 1638109
  stamp: 
    secs: 1742317251
    nsecs: 307865235
  frame_id: "imu_0"
orientation: 
  x: -0.6633602375828037
  y: 0.09384436044594946
  z: 0.08440128180228447
  w: 0.7375790498900496
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.19040856108961332
  y: 0.15965331155694223
  z: 0.09235523081063989
angular_velocity_covariance: [2.7474e-06, 0.0, 0.0, 0.0, 2.7474e-06, 0.0, 0.0, 0.0, 7.312e-06]
linear_acceleration: 
  x: -2.6242133618354795
  y: -9.737442608261107
  z: 1.0926163732528686
linear_acceleration_covariance: [0.00041915, 0.0, 0.0, 0.0, 0.00041915, 0.0, 0.0, 0.0, 1.8995e-05]
---
header: 
  seq: 1638110
  stamp: 
    secs: 1742317251
    nsecs: 313860151
  frame_id: "imu_0"
orientation: 
  x: -0.6620558419374131
  y: 0.0951419884302892
  z: 0.08529573481732369
  w: 0.738481348319676
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.18270350342379607
  y: 0.1445041860121355
  z: 0.1009529800738517
angular_velocity_covariance: [2.7474e-06, 0.0, 0.0, 0.0, 2.7474e-06, 0.0, 0.0, 0.0, 7.312e-06]
linear_acceleration: 
  x: -2.689586289978027
  y: -9.735048406600951
  z: 1.143455749130249
linear_acceleration_covariance: [0.00041915, 0.0, 0.0, 0.0, 0.00041915, 0.0, 0.0, 0.0, 1.8995e-05]
---
header: 
  seq: 1638111
  stamp: 
    secs: 1742317251
    nsecs: 317853739
  frame_id: "imu_0"
orientation: 
  x: -0.6598041655620079
  y: 0.09650486823242568
  z: 0.08601920142153245
  w: 0.7402337269412049
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.1689083289771856
  y: 0.12685488483596236
  z: 0.10274368959082097
angular_velocity_covariance: [2.7474e-06, 0.0, 0.0, 0.0, 2.7474e-06, 0.0, 0.0, 0.0, 7.312e-06]
linear_acceleration: 
  x: -2.776619261264801
  y: -9.80612626838684
  z: 1.143455749130249
linear_acceleration_covariance: [0.00041915, 0.0, 0.0, 0.0, 0.00041915, 0.0, 0.0, 0.0, 1.8995e-05]
---
header: 
  seq: 1638112
  stamp: 
    secs: 1742317251
    nsecs: 319872133
  frame_id: "imu_0"
orientation: 
  x: -0.6570643243977176
  y: 0.0980985594138642
  z: 0.086826767704763
  w: 0.7423639664306443
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.15727990239346362
  y: 0.11604458133911273
  z: 0.10915551623129575
angular_velocity_covariance: [2.7474e-06, 0.0, 0.0, 0.0, 2.7474e-06, 0.0, 0.0, 0.0, 7.312e-06]
linear_acceleration: 
  x: -2.7951743241310116
  y: -9.775936881828308
  z: 1.3320178345680236
linear_acceleration_covariance: [0.00041915, 0.0, 0.0, 0.0, 0.00041915, 0.0, 0.0, 0.0, 1.8995e-05]
---
header: 
  seq: 1638113
  stamp: 
    secs: 1742317251
    nsecs: 321866269
  frame_id: "imu_0"
orientation: 
  x: -0.6533236086217793
  y: 0.10051413043613018
  z: 0.0881235255513696
  w: 0.7451841492171462
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.13601189792809082
  y: 0.10091036949641043
  z: 0.1176030632090271
angular_velocity_covariance: [2.7474e-06, 0.0, 0.0, 0.0, 2.7474e-06, 0.0, 0.0, 0.0, 7.312e-06]
linear_acceleration: 
  x: -2.8171710518836974
  y: -9.740510179138184
  z: 1.3940987354278565
linear_acceleration_covariance: [0.00041915, 0.0, 0.0, 0.0, 0.00041915, 0.0, 0.0, 0.0, 1.8995e-05]
---
header: 
  seq: 1638114
  stamp: 
    secs: 1742317251
    nsecs: 329853006
  frame_id: "imu_0"
orientation: 
  x: -0.6507774587959236
  y: 0.10238929981121202
  z: 0.08919713541220767
  w: 0.7470267742467774
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.11518278241036309
  y: 0.09039407898390553
  z: 0.12668231199732524
angular_velocity_covariance: [2.7474e-06, 0.0, 0.0, 0.0, 2.7474e-06, 0.0, 0.0, 0.0, 7.312e-06]
linear_acceleration: 
  x: -2.8640824406623837
  y: -9.753603469467162
  z: 1.456291864490509
linear_acceleration_covariance: [0.00041915, 0.0, 0.0, 0.0, 0.00041915, 0.0, 0.0, 0.0, 1.8995e-05]
---
```
